theme: lynx
title: Hi!
enableEmoji: yes
disableKinds:
  - taxonomy
  - term
author:
  headline: A PhD researcher in cognitive neuroscience at the BCBL (Spain).
  image: author.jpg
  links:
    - link:
        href: https://github.com/jpanther/lynx/blob/stable/README.md
        icon: github
        text: My CV
    - link:
        href: styles/
        target: _self
        text: Projects I'm working on
    - github: https://github.com/lauradefrutos
    - twitter: https://twitter.com/laura3141592
  name: Hi! My name is Laura de Frutos-Sagastuy.
markup:
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    noClasses: no
