theme: lynx
title: Hi!
enableEmoji: yes
disableKinds:
  - taxonomy
  - term
author:
  headline: A PhD researcher in cognitive neuroscience at the BCBL (Spain).
  image: foto_carnet_2020.jpg
  links:
    - cv:
        icon: christmas-socks-svgrepo-com
        target: _self
        text: My CV
    - link:
        href: projects/
        icon: christmas-socks-svgrepo-com
        target: _self
        text: Projects I'm working on
    - link:
        href: 
        icon:
        text: About me
    - github:
        href: https://github.com/lauradefrutos
        text: Github 
    - twitter:
        href: https://twitter.com/laura3141592
        text: Twitter
    - orcid:
        href: https://orcid.org/0000-0003-0027-3116
        text: ORCID
  name: Hi! My name is Laura de Frutos-Sagastuy.
markup:
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    noClasses: no
